# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Generated by quent-schema-codegen-python from quent/model.yaml.
from __future__ import annotations

from collections.abc import Callable, Mapping
from os import PathLike
from typing import Generic, TypeVar, TypedDict

T = TypeVar("T")

def model_qmi() -> str: ...

class Uuid:
    def __init__(self, value: str) -> None: ...
    def __str__(self) -> str: ...

class ExporterOptions:
    @staticmethod
    def none() -> ExporterOptions: ...
    @staticmethod
    def ndjson(output_dir: str | PathLike[str]) -> ExporterOptions: ...
    @staticmethod
    def callback(callback: Callable[[str], object]) -> ExporterOptions: ...

class ImplementationDict(TypedDict):
    name: str
    version: str
    backend: str
    custom_attributes: Mapping[str, bool | int | float | str | None]

class OperatorStatisticsDict(TypedDict):
    input_bytes: int
    output_bytes: int
    output_rows: int | None
    chunk_count: int
    duplicated: bool
    decision: str | None

class Context:
    def __init__(self, options: ExporterOptions | None = None) -> None: ...
    @property
    def id(self) -> Uuid: ...
    def close(self) -> None: ...
    def engine_observer(self) -> Observer[EngineHandle]: ...
    def query_group_observer(self) -> Observer[QueryGroupHandle]: ...
    def worker_observer(self) -> Observer[WorkerHandle]: ...
    def plan_observer(self) -> Observer[PlanHandle]: ...
    def operator_observer(self) -> Observer[OperatorHandle]: ...
    def port_observer(self) -> Observer[PortHandle]: ...
    def thread_pool_observer(self) -> Observer[ThreadPoolHandle]: ...
    def processor_observer(self) -> Observer[ProcessorHandle]: ...
    def memory_observer(self) -> Observer[MemoryHandle]: ...
    def data_channel_observer(self) -> Observer[DataChannelHandle]: ...
    def query_observer(self) -> Observer[QueryHandle]: ...
    def evaluate_observer(self) -> Observer[EvaluateHandle]: ...
    def actor_observer(self) -> Observer[ActorHandle]: ...

class Observer(Generic[T]):
    def create(self, id: Uuid | None = None) -> T: ...

class Handle:
    @property
    def entity_uuid(self) -> Uuid: ...

class EngineHandle(Handle):
    def init(
        self, *, instance_name: str, implementation: ImplementationDict
    ) -> None: ...
    def exit(self) -> None: ...

class QueryGroupHandle(Handle):
    def declared(
        self, *, instance_name: str | None, engine: EngineHandle | Uuid
    ) -> None: ...

class WorkerHandle(Handle):
    def init(
        self,
        *,
        instance_name: str,
        engine: EngineHandle | Uuid,
        parent_engine_id: str,
    ) -> None: ...
    def exit(self) -> None: ...

class PlanHandle(Handle):
    def declared(
        self,
        *,
        instance_name: str,
        query: QueryHandle | Uuid,
        parent_plan: PlanHandle | Uuid | None,
        worker: WorkerHandle | Uuid | None,
        edges: list[Mapping[str, object]],
    ) -> None: ...

class OperatorHandle(Handle):
    def declared(
        self,
        *,
        plan: PlanHandle | Uuid,
        parent_operators: list[OperatorHandle | Uuid],
        instance_name: str,
        type_name: str,
        attributes: Mapping[str, bool | int | float | str | None],
    ) -> None: ...
    def statistics(self, *, values: OperatorStatisticsDict) -> None: ...

class PortHandle(Handle):
    def declared(
        self, *, operator: OperatorHandle | Uuid, instance_name: str
    ) -> None: ...

class ThreadPoolHandle(Handle):
    def declared(self, *, instance_name: str, worker: WorkerHandle | Uuid) -> None: ...

class ProcessorHandle(Handle):
    def declared(
        self, *, instance_name: str, thread_pool: ThreadPoolHandle | Uuid
    ) -> None: ...

class MemoryHandle(Handle):
    def declared(
        self,
        *,
        instance_name: str,
        resource_type: str,
        worker: WorkerHandle | Uuid,
        limits: Mapping[str, int],
    ) -> None: ...

class DataChannelHandle(Handle):
    def declared(
        self,
        *,
        instance_name: str,
        channel_type: str,
        worker: WorkerHandle | Uuid,
        source: MemoryHandle | Uuid,
        target: MemoryHandle | Uuid,
    ) -> None: ...

class QueryHandle(Handle):
    def initialized(
        self, *, instance_name: str, query_group: QueryGroupHandle | Uuid
    ) -> None: ...
    def planning(self) -> None: ...
    def executing(self) -> None: ...
    def exited(self) -> None: ...

class EvaluateHandle(Handle):
    def queued(
        self,
        *,
        instance_name: str,
        operator: OperatorHandle | Uuid,
        worker: WorkerHandle | Uuid,
    ) -> None: ...
    def running(
        self,
        *,
        io: bool,
        input_bytes: int,
        processor: Mapping[str, object] | None,
        memory: Mapping[str, object] | None,
        channel: Mapping[str, object] | None,
    ) -> None: ...
    def exited(self, *, succeeded: bool, output_bytes: int) -> None: ...

class ActorHandle(Handle):
    def started(
        self, *, operator: OperatorHandle | Uuid, worker: WorkerHandle | Uuid
    ) -> None: ...
    def running(self) -> None: ...
    def exited(
        self,
        *,
        input_bytes: int,
        output_bytes: int,
        output_rows: int | None,
        chunk_count: int,
        duplicated: bool,
        decision: str | None,
    ) -> None: ...
