[workspace]

[package]
name = "cudf-polars-quent"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "_quent"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29", features = ["abi3-py311"] }
quent-dynamic-attributes = { git = "https://github.com/rapidsai/quent", rev = "074319821341d83932efff90eb71f075a89618ab" }
quent-instrumentation = { git = "https://github.com/rapidsai/quent", rev = "074319821341d83932efff90eb71f075a89618ab", features = ["serde", "io-callback", "io-ndjson"] }
quent-io = { git = "https://github.com/rapidsai/quent", rev = "074319821341d83932efff90eb71f075a89618ab", default-features = false, features = ["ndjson"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
quent-build-info = { git = "https://github.com/rapidsai/quent", rev = "074319821341d83932efff90eb71f075a89618ab" }
quent-instrumentation-build = { git = "https://github.com/rapidsai/quent", rev = "074319821341d83932efff90eb71f075a89618ab" }
quent-schema-codegen-python = { git = "https://github.com/rapidsai/quent", rev = "074319821341d83932efff90eb71f075a89618ab" }
quent-yaml = { git = "https://github.com/rapidsai/quent", rev = "074319821341d83932efff90eb71f075a89618ab" }
